#!/bin/bash

# Launch rofimoji with a whole bunch of "include files" flags
#
# used via solaar as a highly broad emoji picker

rofimoji --action copy --files emojis alchemical_symbols arrows block_elements box_drawing chess_symbols combining_diacritical_marks combining_diacritical_marks_extended combining_diacritical_marks_for_symbols combining_diacritical_marks_supplement combining_half_marks currency_symbols dingbats emoticons general_punctuation geometric_shapes greek_and_coptic ideographic_description_characters ipa_extensions latin-1_supplement latin_extended-a latin_extended-b latin_extended-c latin_extended-d latin_extended-e latin_extended-f latin_extended-g latin_extended_additional letterlike_symbols math mathematical_alphanumeric_symbols mathematical_operators miscellaneous_mathematical_symbols-a miscellaneous_mathematical_symbols-b miscellaneous_symbols miscellaneous_symbols_and_pictographs miscellaneous_technical number_forms ornamental_dingbats phonetic_extensions phonetic_extensions_supplement playing_cards small_form_variants superscripts_and_subscripts supplemental_arrows-a supplemental_arrows-b supplemental_arrows-c supplemental_punctuation supplemental_symbols_and_pictographs symbols_and_pictographs_extended-a symbols_for_legacy_computing transport_and_map_symbols vertical_forms
