#!/bin/bash

pkill -x dunst

# Get Wal color file
SRC=${HOME}"/.cache/wal/colors"
[[ ! -e $SRC ]] && exit 0

READLINK=$( command -v greadlink | command -v readlink )

# Get config file
if [[ $1 ]]; then
	# Check path syntax here
	[[ -e $1 ]] && CFG=$1
	[[ -L $1 ]] && CFG=$($READLINK -f $1)
	[[ ! -e $1 ]] && exit 0
else
	# Default config path
	[[ -e ${HOME}"/.config/dunst/dunstrc" ]] && CFG=${HOME}"/.config/dunst/dunstrc"
	[[ -L ${HOME}"/.config/dunst/dunstrc" ]] && CFG=$($READLINK -f ${HOME}"/.config/dunst/dunstrc")
	[[ ! -e $CFG ]] && exit 0
fi

# Get and convert hex colors from Wal cache
index=1
for line in $(grep -oE '[0-9a-fA-F]{6}' "$SRC")
do
	regex='[0-9a-fA-F]{6}'
	if [[ $line =~ $regex ]]
	then
		eval "color$index=#$line"
		index=$((index+1));
	fi
done

# Delete existing color declerations (generated by this script)
if grep -q '^# BEGIN DCE' "$CFG"; then
	sed -i '' -e '/^# BEGIN DCE/,/^# END DCE/{/^# BEGIN DCE/!{/^# END DCE/!d;};}' "$CFG"
# ^^^ There's something wrong with this command. If BEGIN ACE comment
# doesn't exist but END ACE, just deletes all config except END ACE line.
# In the mean time, surrounding comments must not touched, until finding
# safer version of this command.
else
	echo -e '# BEGIN DCE\n# END ACE' >> "$CFG";
fi

# vvv This line may give error on different systems.
sed -i '' -e "/^# BEGIN DCE/ r /dev/stdin" "$CFG" <<EOF
[urgency_low]
    # IMPORTANT: colors have to be defined in quotation marks.
    # Otherwise the "#" and following would be interpreted as a comment.
    background = "$color1"
    foreground = "$color8"
    frame_color = "$color3"
    timeout = 5

[urgency_normal]
    background = "$color1"
    foreground = "$color8"
    frame_color = "$color5"
    timeout = 10

[urgency_critical]
    background = "$color1"
    foreground = "$color8"
    frame_color = "$color2"
    timeout = 20
EOF

dunst &
